# Generated by Django 4.2.4 on 2023-09-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_code_ck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('auth_code', models.CharField(max_length=100)),
                ('val', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Auth_code',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_img', models.ImageField(upload_to='lecture_img')),
                ('company', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('live_time', models.CharField(max_length=1000)),
                ('lecture_text', models.CharField(max_length=10000)),
                ('runnig_time', models.CharField(max_length=1000)),
                ('urls', models.CharField(default=None, max_length=1000, null=True)),
                ('live', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Lecture',
            },
        ),
        migrations.CreateModel(
            name='User_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'User_table',
            },
        ),
    ]
