# Generated by Django 4.2.4 on 2023-09-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_code_ck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('auth_code', models.CharField(max_length=100)),
                ('val', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Auth_code',
            },
        ),
    ]
