# Generated by Django 4.2.4 on 2023-09-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'User_table',
            },
        ),
    ]
