# Generated by Django 4.2.4 on 2023-09-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpg', '0002_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_img', models.ImageField(upload_to='lecture_img')),
                ('company', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=50)),
                ('live_time', models.CharField(max_length=1000)),
                ('lecture_text', models.CharField(max_length=10000)),
                ('runnig_time', models.CharField(max_length=1000)),
                ('live', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Lecture',
            },
        ),
    ]
