# Generated by Django 4.2.4 on 2023-09-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpg', '0002_alter_lecture_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='live',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
